%% train_net.m
% Train the twin (Siamese) network on natural-image near/far patch pairs, sampled
% fresh on the fly (never repeating). Test/validate on a balanced same/different
% texture-pair set combining several texture databases (cross-domain transfer),
% loaded from a .mat produced by texture_same_diff_patches_net.
% Run from the repo root with twin-net/ on the MATLAB path (run setup first).

clearvars
clc

down_level = 1;     % resolution scale-down (1,2,4,8); MUST match the level used
                    % when generating the texture test pairs
gpu = gpuDevice([]);

%% Build the training data (natural-image near/far pairs, sampled on the fly)
% On-the-fly sampling (net_plan.md): build the pool of achromatic (A) source images
% once, then cut fresh, non-repeating patch pairs each iteration, so there is nothing
% to memorize. ALL shared parameters (optics, image list, patch size, normalization)
% come from config.m -- the single source also used by the Bayesian pipeline, so they
% cannot diverge. Ingestion runs through the shared vislab.nat_stat_bayes.source_to_lms.
cfg = config;
psz = cfg.patch.size;        % patch size (matches the [64 64 1] network input)
same_max_dist = 1;           % max neighbor offset (in patches) for the near pair (network sampling)

% expensive one-time step: process every source image into its A channel
A_pool = load_nat_A_pool(cfg, down_level);

% Split the IMAGE list (not pairs) into 90% train / 10% val, so validation patches
% come from images the network never trains on.
n_img = numel(A_pool);
perm = randperm(n_img);
nTrainImg = round(0.9 * n_img);
A_pool_train = A_pool(perm(1:nTrainImg));
A_pool_val   = A_pool(perm(nTrainImg+1:end));
% A_pool stays in CPU RAM; only the small per-batch arrays go to the GPU.

%% Load the texture test data (same/different pairs; Bayesian-mirrored ingestion)
% Generated by texture_same_diff_patches_net. Two test sets:
%   same,      diff       -- all databases combined (brodatz/fabric/mcgill/vistex/pertex,
%                            balanced), "different" pairs may cross databases
%   same_brod, diff_brod  -- Brodatz only
% label 1 = same texture, 0 = different.
if down_level>1
    bpfile = fullfile(cfg.paths.stimuli, 'textures', ['patch_pairs_dsmpl_' num2str(down_level) '.mat']);
else
    bpfile = fullfile(cfg.paths.stimuli, 'textures', 'patch_pairs.mat');
end
load(bpfile,'same','diff','same_brod','diff_brod');

%% Define Network Architecture
% Shared subnetwork. Five selectable architectures; all output an H x W x nChan map
% that poolStats reduces to a 2*nChan-vector (nChan channel means + nChan stds) per patch.
arch = "pyramid";   % "baseline" | "dilated" | "multiscale" | "pyramid" | "pyramid_wide"

switch arch
    case "baseline"
        % Original: 4x (conv -> relu -> maxpool), valid padding -> 4x4x32 final map.
        layers = [
            imageInputLayer([64 64 1],Normalization=@(img) img/mean(img(:))) % 64x64
            convolution2dLayer(5,8,WeightsInitializer="narrow-normal",BiasInitializer="narrow-normal") % 60x60 x8
            reluLayer
            maxPooling2dLayer(2,Stride=2) % 30x30
            convolution2dLayer(5,16,WeightsInitializer="narrow-normal",BiasInitializer="narrow-normal") % 26x26 x16
            reluLayer
            maxPooling2dLayer(2,Stride=2) % 13x13
            convolution2dLayer(4,16,WeightsInitializer="narrow-normal",BiasInitializer="narrow-normal") % 10x10 x16
            reluLayer
            maxPooling2dLayer(2,Stride=2) % 5x5
            convolution2dLayer(2,32,WeightsInitializer="narrow-normal",BiasInitializer="narrow-normal") % 4x4 x32
            reluLayer];
        nChan = 32;

    case "dilated"
        % Dilated variant: grow the receptive field with DilationFactor instead of
        % pooling. Keep only the first maxpool (it cheaply shrinks the large early map);
        % drop the other two. Dilations 1-2-2-2 give a receptive field of ~38 px (close to
        % the baseline's ~40) while leaving a 14x14x32 final map -- ~196 spatial samples for
        % poolStats vs the baseline's 16. Effective kernel = dilation*(k-1)+1.
        layers = [
            imageInputLayer([64 64 1],Normalization=@(img) img/mean(img(:)))                                          % 64x64
            convolution2dLayer(5,8, WeightsInitializer="narrow-normal",BiasInitializer="narrow-normal")               % 60x60 x8
            reluLayer
            maxPooling2dLayer(2,Stride=2)                                                                             % 30x30
            convolution2dLayer(5,16,DilationFactor=2,WeightsInitializer="narrow-normal",BiasInitializer="narrow-normal") % 22x22 x16 (keff 9)
            reluLayer
            convolution2dLayer(4,16,DilationFactor=2,WeightsInitializer="narrow-normal",BiasInitializer="narrow-normal") % 16x16 x16 (keff 7)
            reluLayer
            convolution2dLayer(2,32,DilationFactor=2,WeightsInitializer="narrow-normal",BiasInitializer="narrow-normal") % 14x14 x32 (keff 3)
            reluLayer];
        nChan = 32;

    case "multiscale"
        % V1-like parallel multi-scale bank: a first-layer bank of 3x3 convs at
        % DilationFactor 1/2/4 (fine/medium/coarse scale), each Padding="same" so the
        % three 64x64x8 outputs align, depth-concatenated into 64x64x24 parallel
        % spatial-frequency channels. A shared tail reduces that to a 12x12x32 map.
        % Built as a layerGraph (branched DAG); dlnetwork() accepts it directly.
        % NOTE: the bank adds parameters vs the linear stacks -- watch for overfitting.
        dils = [1 2 4];
        lgraph = layerGraph();
        lgraph = addLayers(lgraph, ...
            imageInputLayer([64 64 1],Normalization=@(img) img/mean(img(:)),Name="in"));           % 64x64
        for i = 1:numel(dils)
            branch = [
                convolution2dLayer(3,8,DilationFactor=dils(i),Padding="same", ...
                    WeightsInitializer="narrow-normal",BiasInitializer="narrow-normal",Name="b"+i+"_conv") % 64x64 x8
                reluLayer(Name="b"+i+"_relu")];
            lgraph = addLayers(lgraph, branch);
            lgraph = connectLayers(lgraph, "in", "b"+i+"_conv");
        end
        lgraph = addLayers(lgraph, depthConcatenationLayer(numel(dils),Name="cat"));                % 64x64 x24
        for i = 1:numel(dils)
            lgraph = connectLayers(lgraph, "b"+i+"_relu", "cat/in"+i);
        end
        tail = [
            maxPooling2dLayer(2,Stride=2,Name="pool1")                                                              % 32x32
            convolution2dLayer(5,16,WeightsInitializer="narrow-normal",BiasInitializer="narrow-normal",Name="t_conv1") % 28x28 x16
            reluLayer(Name="t_relu1")
            maxPooling2dLayer(2,Stride=2,Name="pool2")                                                              % 14x14
            convolution2dLayer(3,32,WeightsInitializer="narrow-normal",BiasInitializer="narrow-normal",Name="t_conv2") % 12x12 x32
            reluLayer(Name="t_relu2")];
        lgraph = addLayers(lgraph, tail);
        lgraph = connectLayers(lgraph, "cat", "pool1");
        layers = lgraph;   % dlnetwork() accepts a layerGraph as well as a plain layer array
        nChan = 32;

    case "pyramid"
        % Lean Gaussian-pyramid front end: three average-pooled scales (1/2/4), a
        % 5x5x8 conv per scale, each resized to a common 12x12 and depth-concatenated
        % into 12x12x24 multi-scale channels, then a single 3x3x32 tail conv -> 10x10x32.
        % ~7.6k learned params (leaner than the 9.7k baseline). Average-pool is a box
        % approximation to a Gaussian pyramid (a Laplacian variant would take level
        % differences). Built as a layerGraph; needs resize2dLayer (Image Processing Toolbox).
        cs = 12;   % common spatial size for the concat
        lgraph = layerGraph();
        lgraph = addLayers(lgraph, ...
            imageInputLayer([64 64 1],Normalization=@(img) img/mean(img(:)),Name="in"));    % 64x64
        % scale 1 (full resolution)
        lgraph = addLayers(lgraph, [
            convolution2dLayer(5,8,WeightsInitializer="narrow-normal",BiasInitializer="narrow-normal",Name="p0_conv") % 60x60 x8
            reluLayer(Name="p0_relu")
            resize2dLayer(OutputSize=[cs cs],Method="bilinear",Name="p0_rs")]);              % 12x12 x8
        lgraph = connectLayers(lgraph, "in", "p0_conv");
        % scale 1/2
        lgraph = addLayers(lgraph, [
            averagePooling2dLayer(2,Stride=2,Name="p1_pool")                                 % 32x32
            convolution2dLayer(5,8,WeightsInitializer="narrow-normal",BiasInitializer="narrow-normal",Name="p1_conv") % 28x28 x8
            reluLayer(Name="p1_relu")
            resize2dLayer(OutputSize=[cs cs],Method="bilinear",Name="p1_rs")]);              % 12x12 x8
        lgraph = connectLayers(lgraph, "in", "p1_pool");
        % scale 1/4 (already 12x12 after the conv, no resize needed)
        lgraph = addLayers(lgraph, [
            averagePooling2dLayer(4,Stride=4,Name="p2_pool")                                 % 16x16
            convolution2dLayer(5,8,WeightsInitializer="narrow-normal",BiasInitializer="narrow-normal",Name="p2_conv") % 12x12 x8
            reluLayer(Name="p2_relu")]);
        lgraph = connectLayers(lgraph, "in", "p2_pool");
        % merge the three scales and reduce to a 32-channel map
        lgraph = addLayers(lgraph, depthConcatenationLayer(3,Name="cat"));                   % 12x12 x24
        lgraph = connectLayers(lgraph, "p0_rs",   "cat/in1");
        lgraph = connectLayers(lgraph, "p1_rs",   "cat/in2");
        lgraph = connectLayers(lgraph, "p2_relu", "cat/in3");
        lgraph = addLayers(lgraph, [
            convolution2dLayer(3,32,WeightsInitializer="narrow-normal",BiasInitializer="narrow-normal",Name="t_conv") % 10x10 x32
            reluLayer(Name="t_relu")]);
        lgraph = connectLayers(lgraph, "cat", "t_conv");
        layers = lgraph;
        nChan = 32;

    case "pyramid_wide"
        % Slightly bigger "pyramid": SAME 3-scale front end and per-scale channels as the
        % lean pyramid (bc = 8); only the tail is widened (nChan 32 -> 48, embedding 96) --
        % ~11k learned params, just above the 7.6k lean pyramid. An earlier 29k version
        % (bc = 16, nChan = 64) raised accuracy but erased the Brodatz-over-nat edge, so
        % keep the capacity bump small.
        % WATCH: with on-the-fly sampling there is no memorization to overfit, but extra
        % capacity can lock onto natural-specific structure. Pass/fail = whether Brodatz
        % stays >= test(nat). (bc, nChan are the capacity knobs -- sweep to trade off.)
        cs = 12;    % common spatial size for the concat
        bc = 8;     % channels per scale (same as the lean pyramid)
        lgraph = layerGraph();
        lgraph = addLayers(lgraph, ...
            imageInputLayer([64 64 1],Normalization=@(img) img/mean(img(:)),Name="in"));     % 64x64
        lgraph = addLayers(lgraph, [
            convolution2dLayer(5,bc,WeightsInitializer="narrow-normal",BiasInitializer="narrow-normal",Name="p0_conv") % 60x60
            reluLayer(Name="p0_relu")
            resize2dLayer(OutputSize=[cs cs],Method="bilinear",Name="p0_rs")]);               % 12x12
        lgraph = connectLayers(lgraph, "in", "p0_conv");
        lgraph = addLayers(lgraph, [
            averagePooling2dLayer(2,Stride=2,Name="p1_pool")                                  % 32x32
            convolution2dLayer(5,bc,WeightsInitializer="narrow-normal",BiasInitializer="narrow-normal",Name="p1_conv") % 28x28
            reluLayer(Name="p1_relu")
            resize2dLayer(OutputSize=[cs cs],Method="bilinear",Name="p1_rs")]);               % 12x12
        lgraph = connectLayers(lgraph, "in", "p1_pool");
        lgraph = addLayers(lgraph, [
            averagePooling2dLayer(4,Stride=4,Name="p2_pool")                                  % 16x16
            convolution2dLayer(5,bc,WeightsInitializer="narrow-normal",BiasInitializer="narrow-normal",Name="p2_conv") % 12x12
            reluLayer(Name="p2_relu")]);
        lgraph = connectLayers(lgraph, "in", "p2_pool");
        lgraph = addLayers(lgraph, depthConcatenationLayer(3,Name="cat"));                    % 12x12 x(3*bc)
        lgraph = connectLayers(lgraph, "p0_rs",   "cat/in1");
        lgraph = connectLayers(lgraph, "p1_rs",   "cat/in2");
        lgraph = connectLayers(lgraph, "p2_relu", "cat/in3");
        lgraph = addLayers(lgraph, [
            convolution2dLayer(3,48,WeightsInitializer="narrow-normal",BiasInitializer="narrow-normal",Name="t_conv") % 10x10 x48
            reluLayer(Name="t_relu")]);
        lgraph = connectLayers(lgraph, "cat", "t_conv");
        layers = lgraph;
        nChan = 48;
end

net = dlnetwork(layers);

% merge with fully connected layer: poolStats emits 2*nChan (channel means + stds).
fcWeights = dlarray(0.01*single(randn(1,2*nChan)));
fcBias = dlarray(0.01*single(randn(1,1)));
fcParams = struct("FcWeights",fcWeights,"FcBias",fcBias);

%% train network
numIterations = 5e3;
miniBatchSize = 1e4;
learningRate = 1e-2;
gradDecay = 0.9;
gradDecaySq = 0.99;
executionEnvironment = "auto";
trailingAvgSubnet = [];
trailingAvgSqSubnet = [];
trailingAvgParams = [];
trailingAvgSqParams = [];
% Monitor figure: accuracy curves on top, a montage of the first conv layer's
% learned kernels underneath (both refreshed together at each test iteration).
monitor_fig = figure('Name', 'Training Progress');
monitor_tl = tiledlayout(monitor_fig, 2, 1, 'TileSpacing', 'compact', 'Padding', 'compact');
ax = nexttile(monitor_tl);
grid(ax, 'on');
xlabel(ax, 'Iteration');
ylabel(ax, 'Accuracy');
title(ax, 'Training and Validation Accuracy');

% Light blue, Mid blue, Orange, Green
lineTrain = animatedline(ax, 'DisplayName', 'training (nat)', 'Color', [0.3010 0.7450 0.9330], 'LineWidth', 1.5);
lineNatVal = animatedline(ax, 'DisplayName', 'test (nat)', 'Color', [0 0.4470 0.7410], 'LineWidth', 1.5);
lineTexVal = animatedline(ax, 'DisplayName', 'test (all textures)', 'Color', [1 0.6 0.6], 'LineWidth', 1.5);
lineBrodVal = animatedline(ax, 'DisplayName', 'test (Brodatz)', 'Color', [0.8 0.1 0.1], 'LineWidth', 1.5);
legend(ax, 'show', 'Location', 'southeast');

% Second tile: first-layer kernel montage (drawn in the monitor block below).
axKernels = nexttile(monitor_tl);
title(axKernels, 'conv1 filters');
axis(axKernels, 'image', 'off');
colormap(axKernels, gray);

% OPTIMIZATION: Pre-load fixed texture validation batches to the GPU (all textures +
% Brodatz-only), each reused every check.
[XVal1,XVal2,valLabels] = getTwinBatchPairs(same,diff,miniBatchSize);
XVal1 = dlarray(single(gpuArray(XVal1)),"SSCB");
XVal2 = dlarray(single(gpuArray(XVal2)),"SSCB");
valLabels = gpuArray(valLabels);

[XValB1,XValB2,valLabelsB] = getTwinBatchPairs(same_brod,diff_brod,miniBatchSize);
XValB1 = dlarray(single(gpuArray(XValB1)),"SSCB");
XValB2 = dlarray(single(gpuArray(XValB2)),"SSCB");
valLabelsB = gpuArray(valLabelsB);

% The nat validation batch is drawn fresh from the held-out images at each check
% (inside the loop), not fixed here, so the NatVal curve is an average over many
% held-out pairs rather than one frozen sample.

start = tic;
iteration = 0;

% Loop over mini-batches.
while iteration < numIterations && isvalid(monitor_fig)
    iteration = iteration + 1;

    % Sample a fresh, never-repeating mini-batch of natural-image near/far pairs
    [X1,X2,pairLabels] = getTwinBatch_nat_live(A_pool_train,miniBatchSize,psz,same_max_dist);

    % Patches are cut on the CPU; move the finished batch to the GPU.
    X1 = dlarray(single(gpuArray(X1)),"SSCB");
    X2 = dlarray(single(gpuArray(X2)),"SSCB");
    pairLabels = gpuArray(pairLabels);

    % Evaluate the model loss on training images
    [training_loss,gradientsSubnet,gradientsParams] = dlfeval(@modelLoss,net,fcParams,X1,X2,pairLabels);

    % Measure training accuracy on THIS batch BEFORE the weight update. With the
    % on-the-fly sampler no pair ever repeats, so this batch is fresh data the
    % network has not trained on yet -- measuring it here is an honest held-out-style
    % number that lines up with the validation curves. (Measuring after the update,
    % as before, was optimistically biased because the step just moved the weights
    % toward these exact examples.)
    Y = predictTwin(net,fcParams,X1,X2);

    % OPTIMIZATION: compute accuracy on the GPU, only gather the final scalar
    Y = round(extractdata(Y));
    training_acc = gather(sum(Y == pairLabels)/miniBatchSize);

    % Update training line
    addpoints(lineTrain, iteration, training_acc);

    % Update the twin subnetwork parameters.
    [net,trailingAvgSubnet,trailingAvgSqSubnet] = adamupdate(net,gradientsSubnet, ...
        trailingAvgSubnet,trailingAvgSqSubnet,iteration,learningRate,gradDecay,gradDecaySq);

    % Update the fullyconnect parameters.
    [fcParams,trailingAvgParams,trailingAvgSqParams] = adamupdate(fcParams,gradientsParams, ...
        trailingAvgParams,trailingAvgSqParams,iteration,learningRate,gradDecay,gradDecaySq);

    if mod(iteration, 50) == 0 || iteration == 1
        % Evaluate predictions on the all-textures test set
        YVal = predictTwin(net,fcParams,XVal1,XVal2);
        YVal = round(extractdata(YVal));
        tex_val_acc = gather(sum(YVal == valLabels)/miniBatchSize);
        addpoints(lineTexVal, iteration, tex_val_acc);

        % Evaluate predictions on the Brodatz-only test set
        YValB = predictTwin(net,fcParams,XValB1,XValB2);
        YValB = round(extractdata(YValB));
        brod_val_acc = gather(sum(YValB == valLabelsB)/miniBatchSize);
        addpoints(lineBrodVal, iteration, brod_val_acc);

        % Draw a fresh nat validation batch from the held-out images each check, so
        % NatVal is a new random sample of held-out pairs every time rather than one
        % fixed batch. Kept on held-out images (not the training images) so it still
        % measures generalization to unseen scenes.
        [XValNat1,XValNat2,valLabelsNat] = getTwinBatch_nat_live(A_pool_val,miniBatchSize,psz,same_max_dist);
        XValNat1 = dlarray(single(gpuArray(XValNat1)),"SSCB");
        XValNat2 = dlarray(single(gpuArray(XValNat2)),"SSCB");
        valLabelsNat = gpuArray(valLabelsNat);

        % Evaluate natural image validation accuracy
        YValNat = predictTwin(net,fcParams,XValNat1,XValNat2);
        YValNat = round(extractdata(YValNat));
        nat_val_acc = gather(sum(YValNat == valLabelsNat)/miniBatchSize);
        addpoints(lineNatVal, iteration, nat_val_acc);

        % Refresh the first-layer kernel montage. conv1 = 8 kernels of 5x5x1; each is
        % normalized to [0,1] on its own (so faint filters still show structure) and
        % laid out in a padded grid. net.Learnables holds only the subnet conv weights,
        % so the first "Weights" row is conv1.
        lrn = net.Learnables;
        w1 = gather(extractdata(lrn.Value{find(lrn.Parameter == "Weights", 1)})); % [kh kw 1 nk]
        w1 = squeeze(w1(:,:,1,:));                        % [kh kw nk]
        [kh, kw, nk] = size(w1);
        nCols = ceil(sqrt(2*nk)); nRows = ceil(nk/nCols); % wide-ish grid
        pad = 1;
        mosaic = 0.5 * ones(nRows*(kh+pad)-pad, nCols*(kw+pad)-pad); % mid-grey borders
        for kk = 1:nk
            r = floor((kk-1)/nCols); c = mod(kk-1, nCols);
            k = w1(:,:,kk);
            k = (k - min(k(:))) / (max(k(:)) - min(k(:)) + eps); % per-kernel [0,1]
            mosaic(r*(kh+pad)+(1:kh), c*(kw+pad)+(1:kw)) = k;
        end
        imagesc(axKernels, mosaic, [0 1]);
        colormap(axKernels, gray);
        axis(axKernels, 'image', 'off');
        title(axKernels, sprintf('conv1 filters (%d\\times %d\\times%d)', nk, kh, kw));

        drawnow;
    else
        drawnow limitrate;
    end
end

%% Save the training monitor plot (FIRST, so a later error can't block it)
% Resolve the folder in a way that works in EVERY run mode: mfilename('fullpath') is
% only set on a full Run (empty under Run Section / Evaluate Selection), so fall back
% to which() (finds train_net.m on the path -- setup adds twin-net), then pwd. The
% exportgraphics is wrapped in try/catch so a failure is REPORTED, never silent --
% previously a throw in the net-save below aborted this block before it ran.
if exist('monitor_fig','var') && isvalid(monitor_fig)
    timestamp = char(datetime('now', 'Format', 'yyyy-MM-dd_HH-mm-ss'));
    script_dir = fileparts(mfilename('fullpath'));
    if isempty(script_dir), script_dir = fileparts(which('train_net.m')); end
    if isempty(script_dir), script_dir = pwd; end
    savePath = fullfile(script_dir, ['training_monitor_' timestamp '.png']);
    try
        exportgraphics(monitor_fig, savePath, 'Resolution', 300);
        fprintf('Saved training monitor to %s\n', savePath);
    catch ME
        warning('train_net:monitorSave', 'Could not save monitor figure: %s', ME.message);
    end
else
    warning('train_net:monitorSave', 'monitor_fig missing or closed -- monitor not saved.');
end

%% save the trained network (shipped artifact, kept under data/models)
netdir = fullfile('data','models');
if ~isfolder(netdir), mkdir(netdir); end
if down_level>1
    netfile = fullfile(netdir,['net_on_nat_dsmpl_' num2str(down_level) '.mat']);
else
    netfile = fullfile(netdir,'net_on_nat.mat');
end
save(netfile,'net','fcParams')

%% Test accuracy over five random mini-batches of texture test pairs
accuracy = zeros(1,5);
accuracyBatchSize = 512;

for i = 1:5
    [X1,X2,pairLabelsAcc] = getTwinBatchPairs(same,diff,accuracyBatchSize);
    X1 = dlarray(single(gpuArray(X1)),"SSCB");
    X2 = dlarray(single(gpuArray(X2)),"SSCB");
    Y = predictTwin(net,fcParams,X1,X2);
    Y = gather(extractdata(Y));
    Y = round(Y);
    accuracy(i) = sum(Y == pairLabelsAcc)/accuracyBatchSize;
end

averageAccuracy = mean(accuracy)*100

%% Display test pairs with predictions
testBatchSize = 20;

[XTest1,XTest2,pairLabelsTest] = getTwinBatchPairs(same,diff,testBatchSize);

XTest1 = dlarray(single(gpuArray(XTest1)),"SSCB");
XTest2 = dlarray(single(gpuArray(XTest2)),"SSCB");

% calculate predicted probability
YScore = predictTwin(net,fcParams,XTest1,XTest2);
YScore = gather(extractdata(YScore));

% Convert the predictions to binary 0 or 1.
YPred = round(YScore);
XTest1 = extractdata(XTest1);
XTest2 = extractdata(XTest2);

% Plot images with predicted label and predicted score.
f = figure;
tiledlayout(4,5);

predLabels = categorical(YPred,[0 1],["diff" "same"]);
targetLabels = categorical(pairLabelsTest,[0 1],["diff","same"]);

for i = 1:numel(pairLabelsTest)
    nexttile
    imshow([XTest1(:,:,:,i) XTest2(:,:,:,i)],[]);
    title(string(targetLabels(i)) + " / " + ...
        string(predLabels(i)) + newline + YScore(i))
end
